name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run tests
      run: pytest
    - name: Deploy to GCP
      run: |
        gcloud auth activate-service-account --key-file=$GCP_KEYFILE
        gcloud config set project $GCP_PROJECT
        gcloud app deploy
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_KEYFILE: ${{ secrets.GCP_KEYFILE }}
