name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Set environment variables
      run: echo "DATA_DIR=data" >> $GITHUB_ENV
    - name: Run tests
      run: pytest
    - name: Write GCP key to file
      run: |
        echo "${{ secrets.GCP_KEYFILE }}" > credentials.json
        cat credentials.json  # Debugging line to print the content
    - name: Authenticate to GCP
      run: gcloud auth activate-service-account --key-file=credentials.json
    - name: Set GCP project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}
    - name: Deploy to GCP
      run: gcloud app deploy
