name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Set environment variables
      run: echo "DATA_DIR=data" >> $GITHUB_ENV
    - name: Decode and set up GCP credentials
      env:
        GCP_KEYFILE_BASE64: ${{ secrets.GCP_KEYFILE_BASE64 }}
      run: |
        echo $GCP_KEYFILE_BASE64 | base64 --decode > $HOME/credentials.json
        gcloud auth activate-service-account --key-file=$HOME/credentials.json
        gcloud config set project ${{ secrets.GCP_PROJECT }}
    - name: Run tests
      run: pytest
    - name: Deploy to GCP
      run: |
        gcloud app deploy
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}


        #test